### ISSUE TITLE
During testing，processing of input image

### ISSUE THREAD

**Issue by chuangchuangtan** [junsukchoe/ADL#11]
hi，
I have a question about processing of input image.
For CAM and Has, they resize the input images to 256×256 and average 10 crops (4 corners plus center, and same with horizontal flip) to obtain class probabilities and localization maps. 
For SPG, they directly resize the input images to 224×224. 
But for ADL,you resize the input images to 256×256 and central crop to 224x224.
Is this appropriate? Thank you

**Comment by junsukchoe** [comment]
You are right. Each method uses different pre-processing method during testing.  Previous papers (including ADL) directly compare their methods with other method despite the different pre-processing method. 

The reason why I use the pre-processing method is that I think similar pre-processing methods have to be applied during training and testing. So, I use 256x256 -> 224x224 random crop (training) and 256x256 -> 224x224 center crop (testing).

**Comment by chuangchuangtan** [comment]
It's necessary that following the baseline methods for a fair comparison.

**Comment by junsukchoe** [comment]
It is difficult to compare with previous methods under fair condition in that each method use different configurations (different batch size, training epochs, pre-processing scheme etc.). 

The problem is that each method does not clearly show the configurations. I think that this is why many papers do not reproduce each method, but just bring the scores from the original papers. 

But I totally agree with you. In the future, we will release the scores of each method produced under the fair condition.
